### ISSUE TITLE
请问现在的代码是能够通过cmake编译apollo整个工程的吗？

### ISSUE THREAD

**Issue by cherishTMYY** [minhanghuang/Apollo#1]

**Comment by minhanghuang** [comment]
@cherishTMYY 非常抱歉, 这个仓库暂时不能用Cmake编译Apollo

**Comment by cherishTMYY** [comment]
> @cherishTMYY 非常抱歉, 这个仓库暂时不能用Cmake编译Apollo

感谢您的答复，目前能完成哪些模块的编译啊？

**Comment by minhanghuang** [comment]
> > @cherishTMYY 非常抱歉, 这个仓库暂时不能用Cmake编译Apollo
> 
> 感谢您的答复，目前能完成哪些模块的编译啊？

目前[CyberRT](https://github.com/minhanghuang/CyberRT)可以通过Cmake编译

**Comment by cherishTMYY** [comment]
> > > @cherishTMYY 非常抱歉, 这个仓库暂时不能用Cmake编译Apollo
> > 
> > 
> > 感谢您的答复，目前能完成哪些模块的编译啊？
> 
> 目前[CyberRT](https://github.com/minhanghuang/CyberRT)可以通过Cmake编译

嗯嗯，已经使用了您贡献的CyberRT成功编译了，想问您一下，最近有计划推进一下其他模块修改吗？

**Comment by minhanghuang** [comment]
> > > > @cherishTMYY 非常抱歉, 这个仓库暂时不能用Cmake编译Apollo
> > > 
> > > 
> > > 感谢您的答复，目前能完成哪些模块的编译啊？
> > 
> > 
> > 目前[CyberRT](https://github.com/minhanghuang/CyberRT)可以通过Cmake编译
> 
> 嗯嗯，已经使用了您贡献的CyberRT成功编译了，想问您一下，最近有计划推进一下其他模块修改吗？

目前没有计划使用cmake编译其他模块

**Comment by cherishTMYY** [comment]
> > > > > @cherishTMYY 非常抱歉, 这个仓库暂时不能用Cmake编译Apollo
> > > > 
> > > > 
> > > > 感谢您的答复，目前能完成哪些模块的编译啊？
> > > 
> > > 
> > > 目前[CyberRT](https://github.com/minhanghuang/CyberRT)可以通过Cmake编译
> > 
> > 
> > 嗯嗯，已经使用了您贡献的CyberRT成功编译了，想问您一下，最近有计划推进一下其他模块修改吗？
> 
> 目前没有计划使用cmake编译其他模块

好的，非常感谢您贡献和解答
